firefighting:
  hazard_level: "light"
  steel:
    material: "seamless"
    schedule: "40"
    specs: "ASTM"
    connnection_type: 
      "1": "Threaded"
      "1.25": "Threaded"
      "1.5": "Threaded"
      "2": "Threaded"
      "2.5": "Welded"
      "3": "Welded"
      "4": "Welded"
      "6": "Welded"

processing:
  compute_pipe_dimensions: true

autocad:
  input:
    drawing:
      units: "m"
    root_line_identifier:: 
      color: "red"
    line_network_layer:
      name: "line-network"
    sprinkler_blocks:
      SPR:
        temperature: 68
        k_factor: 5.6 
  output:
    network:
      layer:
        name: "ff-sprinklers"
        properties:
          color: "green"
          line_weight: 0.13
